### ISSUE TITLE
:Denite junkfile junkfile:new not show files

### ISSUE THREAD

**Issue by xerron** [Shougo/junkfile.vim#9]
Vim 8.
Ubuntu 16.04

Install with vim-plug

`      let g:junkfile#directory = '~/Repo/org'`

`     :Denite junkfile junkfile:new`

Not search files of Repo/org

**Comment by Shougo** [comment]
It is wrong usage.

junkfile.vim is not file search plugin.
Closing.

**Comment by xerron** [comment]
How do I edit a file? if you do not show me the files created previously.

:Denite junkfile

No show junk files.

**Comment by Shougo** [comment]
Of course, you must create junkfile before editing.

`:Denite junkfile junkfile:new` or `:JunkfileOpen` is needed.

`junkfile:new` source can create files.

**Comment by Shougo** [comment]
You need to input the filename in denite prompt.
I think you don't know `junkfile:new` usage.

**Comment by xerron** [comment]
with
`:Unite junkfile/new junkfile -start-insert`
I could search the files previously created.
with
`:Denite junkfile junkfile:new `
I can only create files

I understand that now they can only be created.

**Comment by Shougo** [comment]
I cannot reproduce your problem.

**Comment by Shougo** [comment]
I get it.

Please expand your path.

```vim
let g:junkfile#directory = expand('~/Repo/org')
```

**Comment by xerron** [comment]
Thank you. work!
